{% set name = "xrtpy" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xrtpy-{{ version }}.tar.gz
  sha256: aa54ad311858dd9ffa6ac959d92b7f86907791436c45e76226e2fae51ea70dc3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.8
    - setuptools-scm
    - pip
  run:
    - python >=3.8
    - astropy-base >=4.3.1
    - cached-property >=1.5.2
    - matplotlib-base >=3.3.0
    - numpy >=1.20.0
    - packaging
    - scipy >=1.5.0
    - sunpy >=2.0.0

test:
  imports:
    - xrtpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/HinodeXRT/xrtpy
  summary: XRTpy is Python package for analyzing data from the X-Ray Telescope instrument onboard the Hinode spacecraft.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - joyvelasquez
    - namurphy
